name: First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t ci-cd-playground .
      
      - name: Run Docker Container
        run: docker run ci-cd-playground